version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/.github/actions/insert-youtrack-link" # Location of package manifests
    schedule:
      interval: "monthly"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "montly"

  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "montly"